default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["PG_USERNAME"] || "postgres" %>
  password: <%= ENV["PG_PASSWORD"] %>
  host: localhost

development:
  <<: *default
  database: clerk_test_app_development